apiVersion: v1
appVersion: "1.0.0"
name: api
description: A Helm chart for EKS cluster api
version: 0.1.1
kubeVersion: ">=1.14.0-0"
keywords:
  - cluster_api
maintainers:
  - name: bsalgado@monigle.com
