name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          path: api 

      - name: Build, tag, and push image to Amazon ECR
# env:
#   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#   ECR_REPOSITORY: beam3-api
#   IMAGE_TAG: ${{ github.sha }}  
        run: |
          cd api/application/api
          docker build -t sample_api  .
# docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
   
  # deploy:
  #   runs-on: ubuntu
  #   needs: build
  #   steps:

  #     - name: Check out the repo
  #       uses: actions/checkout@v3          

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v1      

  #     - name: Deploy helm
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: beam3-api
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         aws eks --region us-east-1 update-kubeconfig --name brayest-dev
  #         helm upgrade -i -n default api application/deploy/api \
  #                                   --set image.tag=$IMAGE_TAG \
  #                                   --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
  #                                   --set settings.domain=brayest.com \
  #                                   --set settings.environment=qa \
  #                                   --set replicaCount=3 
                              